version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: physioflow_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: physioflow_db
    ports:
      - "5432:5432"
    volumes:
      - physioflow_pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: physioflow_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@physioflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  physioflow_pgdata:
